Repository KarlaOg/PA_ESGI_4IW3, pull requests merged in 2021-04, with the labels that each got.

#42 Feature/partnership
  .gitignore
  README.md
  src/Controller/OfferController.php
  src/Controller/UsersController.php
  src/Entity/Application.php
  src/Entity/Influencer.php
  src/Entity/Offer.php
  src/Form/OfferType.php
  src/Repository/InfluencerRepository.php
  templates/offer/index.html.twig
  templates/offer/show.html.twig
  templates/shared/_navbar.html.twig
  templates/users/offers.html.twig
Labels: bug, help wanted

#36 Ajout de la suppression d'un utilisateur
  app/guestbook-5.2.zip
  app/migrations/Version20210401214400.php
  app/node_modules/.yarn-integrity
  app/package-lock.json
  app/symfony.lock
  app/vendor/composer/package-versions-deprecated/src/PackageVersions/Versions.php
  app/yarn.lock
  assets/app.js
  assets/app.scss
  composer.lock
  package.json
  public/css/account.css
  src/Controller/UsersController.php
  src/Entity/Brand.php
  src/Entity/Influencer.php
  src/Entity/User.php
  templates/base.html.twig
  templates/users/deleteProfile.html.twig
  templates/users/editprofile.html.twig
Labels: enhancement

#41 Fix : afficher seulement les offres dont la date de fin est supérieure au jour actuel
  src/Controller/OfferController.php
  templates/offer/index.html.twig
  templates/offer/show.html.twig
Labels: bug, to review

#55 [DONE] Button Disabled if user already applied
  src/Controller/BrandController.php
  src/Controller/OfferController.php
  src/Repository/ApplicationRepository.php
  templates/brand/show.html.twig
  templates/offer/index.html.twig
  templates/offer/show.html.twig
  templates/shared/_navbar.html.twig
  templates/users/offers.html.twig
Labels: to review

#49 Add redirect home if user register
  src/Controller/RegisterController.php
  src/Form/RegisterType.php
Labels: to review

#47 [WIP]:fix : change Entity
  README.md
  node_modules/.yarn-integrity
  package.json
  src/Controller/Admin/OffersController.php
  src/Controller/BrandController.php
  src/Controller/OfferController.php
  src/Controller/RegisterController.php
  src/Controller/UsersController.php
  src/DataFixtures/AppFixtures.php
  src/Entity/Application.php
  src/Entity/Brand.php
  src/Entity/Influencer.php
  src/Entity/Offer.php
  src/Entity/Payment.php
  src/Entity/User.php
  src/Form/EditBrandType.php
  src/Repository/BrandRepository.php
  src/Repository/InfluencerRepository.php
  src/Repository/OfferRepository.php
  src/Security/Voter/OfferVoter.php
  tailwind.config.js
  templates/admin/base_admin.html.twig
  templates/admin/edit_offer.html.twig
  templates/admin/index.html.twig
  templates/admin/list_offers.html.twig
  templates/admin/list_users.html.twig
  templates/home/index.html.twig
  yarn.lock
Labels: to review
